const EMPLOYER_UPDATE 		= "EMPLOYER_UPDATE";
const TASK_UPDATE 			= "TASK_UPDATE";
const CHIEF_LIST_UPDATE 	= "CHIEF_LIST_UPDATE";
const CUR_EMPLOYER_UPDATE 	= "CUR_EMPLOYER_UPDATE";
const CUR_TASK_UPDATE 		= "CUR_TASK_UPDATE";
const MAX_PRIORITY_UPDATE 	= "MAX_PRIORITY_UPDATE";

export { EMPLOYER_UPDATE, TASK_UPDATE, CHIEF_LIST_UPDATE, 
	CUR_EMPLOYER_UPDATE, CUR_TASK_UPDATE, MAX_PRIORITY_UPDATE };